chain = "sepolia"
native_currency = "sepoliaeth"
transaction_id_prefix = "toad"

[last_sync_block.files]
token_transfers = "../erc20_last_sync_block.txt"
transactions = "../transaction_last_sync_block.txt"

[last_sync_block.block]
token_transfers = 0
transactions = 0
