chain = "sepolia"
native_currency = "sepoliaeth"
transaction_id_prefix = "toad"

[last_sync_time.files]
token_transfers = "../erc20_last_sync_blocktimestamp.txt"
transactions = "../transaction_last_sync_blocktimestamp.txt"

[last_sync_time.start_time]
token_transfers = 0
transactions = 0
