chain = "sepolia"
native_currency = "sepoliaeth"
transaction_id_prefix = "toad_"

[last_sync_time.files]
token_transfers = "../erc20_last_sync_blocktimestamp.txt"
transactions = "../transaction_last_sync_blocktimestamp.txt"

[last_sync_time.start_time]
token_transfers = "2023-01-01 00:00:00.000 +0000"
transactions = "2023-01-01 00:00:00 +0000"
